### ISSUE TITLE
Patch jedi version so that we get tab completion

### ISSUE THREAD

**Issue by jthielen** [Unidata/pyaos-ams-2021#107]
Right now, with the current versions on both https://pyaos-workshop.unidata.ucar.edu and a fresh conda install of the environment.yml file, it seems that tab completion in not working at all. For example, on my local `pyaos-ams-2021` environment, I get the following error whenever I attempt tab completion:

![__init__() got unexpected keyword argument 'column'](https://user-images.githubusercontent.com/3460034/104095771-5b791f00-525e-11eb-8ed0-6aab8eb15894.png)

In my regular dev environment when I ran into this, I just applied the fix suggested here with pip: https://twitter.com/danrothenberg/status/1347703518208036864. In testing this morning, I was also able to get it working with `conda install jedi=0.17.2`, so we should be able to resolve this just by pinning jedi in our `environment.yml`.

Anyone else having this issue? Any objections to getting this fix in before the environment freeze time?

**Comment by jthielen** [comment]
ping @lesserwhirls, @dopplershift, and @julienchastang since we're getting close to the environment cut-off time

**Comment by lesserwhirls** [comment]
I'm checking with Julien now.

**Comment by lesserwhirls** [comment]
Ok, the fix is in and @julienchastang said he will be able to get it on the hub for us. (Thanks @julienchastang!)

**Comment by julienchastang** [comment]
Should be good to go. Please confirm. (I had a couple of problems with users @kpozsonyi and @jthielen, but that should be fixed -- please confirm). Environment should be all set for tomorrow unless I hear otherwise.

**Comment by lesserwhirls** [comment]
Looks good to me! Thank you @julienchastang! Having tab complete will make a huge difference in usability :-)
